In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

# np.ndarray 속성(attribute)

ndarray 클래스의 속성들(attributes)

In [11]:
arr = np.ones(shape=(2,3)) #모든 원소의 값이 1.0인 (2,3)모양의 배열
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [3]:
arr.dtype #배열의 원소들의 데이터 타입

dtype('float64')

In [4]:
arr.shape #모양(shape) : 배열의 각 축(axis)을 따라서 존재하는 원소의 개수 => tuple

(2, 3)

In [12]:
arr.ndim # # 배열의 차원의 개수. 배열의 축(axis)의 개수

2

In [13]:
arr.size # 배열의 전체 원소 개수

6

In [15]:
arr=np.arange(10) # [0,10) 범위의 정수들로 이루어진 1차원 배열.
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
arr.shape

(10,)

In [17]:
arr.ndim

1

In [18]:
# 3차원 배열
arr = np.arange(1, 25).reshape((2, 3, 4))
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [19]:
arr.ndim

3

In [21]:
arr.shape

(2, 3, 4)

In [22]:
arr.dtype

dtype('int64')

# `np.ndarray` indexing

In [24]:
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [25]:
print(arr[0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
print(arr[0,0]) # arr[0,0] - ndarray  / arr[0][0] - list, ndarray

[1 2 3 4]


In [27]:
print(arr[0,0,0]) #arr[0][0][0]

1


* Python list의 인덱스 사용방법: list[a][b][c]...
* numpy ndarray의 인덱스 사용방법:
 * array[a][b][c]...
 * array[a, b, c, ...]

# slicing

## 1차원 배열 slicing

In [28]:
np.random.seed(1)
arr = np.random.randint(100, size= 10) #[0,100) 범위의 정수 난수 10개로 이루어진 1차원 배열.
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [29]:
print(arr[1:5]) # [1,5) 미만 범위의 인덱스의 원소들로 이루어진 1차원 배열

[12 72  9 75]


In [30]:
print(arr[:3]) # 배열에서 첫 3개의 원소들을 slicing

[37 12 72]


In [31]:
print(arr[-3:]) #배열에서 마지막 3개의 원소들을 slicing

[64 16  1]


In [32]:
print(arr[0:1]) # 1차원 배열을 slicing => 1차원 배열

[37]


In [33]:
print(arr[0]) # indexing : 원소 1개 선택

37


## 2차원 배열 slicing

In [34]:
arr = np.arange(20).reshape((4,5))
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [38]:
# 첫 2개 row 선택, 모든 column 선택 => 2차원 배열
print(arr[:2,:])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [40]:
# 첫 2개의 row 선택, 첫 3개의 column 선택
print(arr[:2, :3])

[[0 1 2]
 [5 6 7]]


In [42]:
print(arr[:2][:3]) # 2행 자르고 3행을 잘랐는데, 3행은 아무것도 없어서 위 코드와 다르게 나옴

[[0 1 2 3 4]
 [5 6 7 8 9]]


## 3차원 배열 slicing

In [43]:
# 3차원 배열
arr = np.arange(1, 61).reshape((3, 4, 5))
print(arr)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]

 [[41 42 43 44 45]
  [46 47 48 49 50]
  [51 52 53 54 55]
  [56 57 58 59 60]]]


In [44]:
print(arr[:2,:,:])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]
  [31 32 33 34 35]
  [36 37 38 39 40]]]


In [45]:
print(arr[:1,:,:]) #> 3차원 배열 slicing -> 3차원 배열

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]
  [16 17 18 19 20]]]


In [47]:
print(arr[0,:,:]) # arr[0] -> 2차원 배열
# 인덱스를 통해서 원소를 꺼내게 되면 차원이 줄어든다-> 원소를 꺼내게 되면 scalr

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


# `np.ndarray` 모양(shape) 변경

* `np.ndarray.reshape(shape)`
* `np.ndarray.ravel()`
* `np.ndarray.flatten()`
* `np.newaxis` 이용

## reshape

In [79]:
arr_1d = np.arange(12) #1차원 배열
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [80]:
# 1차원 배열 arr_1d를 (4, 3) shape을 갖는 2D 배열로 변환
arr_2d = arr_1d.reshape((4, 3))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [54]:
# 1차원 배열 arr_1d를 row가 2개인 2D 배열로 변환
# reshape의 argument를 전달할 때, 자동으로 계산할 수 있는 차원의 수는 -1로 대체가능함.
arr_2d = arr_1d.reshape((4, -1))
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [55]:
arr_2d = arr_1d.reshape((-1, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [57]:
# 2차원 배열 - > 1차원 배열
result = arr_2d.reshape((12,))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [58]:
result = arr_2d.reshape(3*4)
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [60]:
result = arr_2d.reshape((-1,))
print(result)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


## `revel` vs `flatten`

In [81]:
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [82]:
flattened = arr_2d.flatten()
# 1차원으로 변환된 배열 "복사본"을 리턴.
# -> 원본(2차원)배열과 별개의 배열을 만들어서 리턴.
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [83]:
flattened[0]=123 # 변환된 1차원 배열의 원소를 변경
print(flattened)
print(arr_2d) #원본 2차원 배열의 원소에는 영향을 미치지 않음.

[123   1   2   3   4   5   6   7   8   9  10  11]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

In [84]:
raveled = arr_2d.ravel()
# 1차원으로 변환된 배열의 "view"를 리턴.
# -> 원본(2차원)배열을 단지 모양만 다르게 보여줌.
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [85]:
raveled[0] =123 # 1차원 배열의 원소를 변경
print(raveled)
print(arr_2d) # 원본(2차원)배열의 원소에 영향을 미침.

[123   1   2   3   4   5   6   7   8   9  10  11]
[[123   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


# `np.newaxis` 속성을 사용한 차원 늘리기

In [89]:
arr = np.arange(5) # (5,) shape의 1차원 배열
print(arr)
print('ndim:', arr.ndim)
print('shape', arr.shape)

[0 1 2 3 4]
ndim: 1
shape (5,)


In [91]:
# arr을 (1,5) shape의 2차원 배열로 변환
result = arr.reshape((1,-1))
print(result)

[[0 1 2 3 4]]


In [93]:
result = arr[np.newaxis,:]
print(result)

[[0 1 2 3 4]]


In [92]:
# arr을 (5,1) shape의 2차원 배열로 변환
result = arr.reshape((-1,1)) #shape=(5,1)
print(result)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [94]:
result = arr[:,np.newaxis]
print(result)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [95]:
print(arr_2d)

[[123   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


In [96]:
result = arr_2d[np.newaxis, : , :]
print(result)

[[[123   1   2]
  [  3   4   5]
  [  6   7   8]
  [  9  10  11]]]


In [97]:
result = arr_2d[:,:,np.newaxis]
print(result)

[[[123]
  [  1]
  [  2]]

 [[  3]
  [  4]
  [  5]]

 [[  6]
  [  7]
  [  8]]

 [[  9]
  [ 10]
  [ 11]]]


## concatenate

* `np.concatenate([a1, a2, ...], axis=0)`: 행 또는 열 방향으로 이어붙이기
* `np.r_[a1, a2]`: 행 이어붙이기(row concatenation)
* `np.c_[a1, a2]`: 열 이어붙이기(column concatenation)

In [98]:
# (2,3) shape 2-d 배열
a1 = np.arange(6).reshape((2,3))
print(a1)

[[0 1 2]
 [3 4 5]]


In [99]:
# (1,3) shape 1-d 배열
a2 = np.array([[10,20,30]])
print(a2)

[[10 20 30]]


In [100]:
# (2,1) shape 2-d 배열
a3 = np.array([[11],[22]])
print(a3)

[[11]
 [22]]


In [101]:
np.concatenate([a1,a2],axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 20, 30]])

In [102]:
np.r_[a1,a2]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 20, 30]])

In [103]:
np.concatenate([a1,a3],axis=1)

array([[ 0,  1,  2, 11],
       [ 3,  4,  5, 22]])

In [104]:
np.c_[a1,a3]

array([[ 0,  1,  2, 11],
       [ 3,  4,  5, 22]])

# Broadcasting
* np.ndarray의 산술연산(+, -, *, /, //, %, ...)은 같은 위치(인덱스)의 원소들끼리(element-wise) 연산이 수행됨.
* 서로 shape이 다른 배열들 사이에서 산술연산이 가능하도록 shape을 맞춰서 연산하는 방법 -> broadcast

In [112]:
a = np.array([1,2,3])   #(3,) shape의 1d 배열
b = np.array([1,2,3,4]) #(4,) shape의 1d 배열
print(a)
print(b)
# a+b
# ValueError 발생 - broadcast가 불가능

[1 2 3]
[1 2 3 4]


## ndarray와 scalar(숫자 한개)의 broadcast 연산

In [113]:
a + 10 

array([11, 12, 13])

In [114]:
a2 = np.arange(6).reshape((2,3))
print(a2)

[[0 1 2]
 [3 4 5]]


In [115]:
a2+10

array([[10, 11, 12],
       [13, 14, 15]])

## 2d 배열과 1d 배열, 또는 2d 배열과 2d 배열에서의 broadcast

In [116]:
a = np.arange(6).reshape((2,3))
print(a)
b= np.arange(10,40,10)
print(b)

[[0 1 2]
 [3 4 5]]
[10 20 30]


In [117]:
a+b

array([[10, 21, 32],
       [13, 24, 35]])

In [122]:
c = np.array([10,20])
# a+c
# operands could not be broadcast together with shapes (2,3) (2,) 

In [123]:
d = c[:, np.newaxis]
print(d)

[[10]
 [20]]


In [124]:
a+d

array([[10, 11, 12],
       [23, 24, 25]])

## broadcast 활용

* 표준화(standardization): 평균이 0이 되고, 표준편차가 1이 되도록 변수들의 스케일을 변환하는 것.
* 정규화(normalization): 최솟값이 0이 되고, 최댓값이 1이 되도록 변수들의 스케일을 변환하는 것.

#표준화

In [147]:
x = np.array([1,2,3,4,5])

In [148]:
mu = np.mean(x) #평균
print(mu)

3.0


In [149]:
sigma = np.std(x) #표준편차
print(sigma)

1.4142135623730951


In [150]:
x_scaled = (x - mu) / sigma #표준화
print(x_scaled)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [132]:
print('평균:',np.mean(x_scaled))
print('표준편차:',np.std(x_scaled))

평균: 0.0
표준편차: 0.9999999999999999


# 정규화

In [151]:
x_sclaed = (x- np.min(x)) / (np.max(x) - np.min(x))
print(x_sclaed)

[0.   0.25 0.5  0.75 1.  ]


### 2차원 배열에서의 표준화, 정규화

In [162]:
# (3,2)
x = np.arange(1,7).reshape((3,2))
print(x)

[[1 2]
 [3 4]
 [5 6]]


In [153]:
np.mean(x) # axis = None (기본값)

3.5

In [154]:
np.mean(x, axis=0) # (1,3,5)의 평균, (2,4,6)의 평균

array([3., 4.])

In [155]:
np.mean(x, axis=1) # (1,2) 의 평균, (3,4)의 평균, (5,6)의 평균

array([1.5, 3.5, 5.5])

In [156]:
np.mean(x, axis=1, keepdims=True)

array([[1.5],
       [3.5],
       [5.5]])

In [165]:
# 표준화 
mu = np.mean(x, axis=0, keepdims=True) #평균
sigma = np.std(x, axis=0, keepdims=True) #표준편차
x_scaled = (x - mu)/sigma
print(x_scaled)

[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]


In [164]:
# 정규화
x_max = np.max(x, axis=0, keepdims=True) #최댓값
x_min = np.min(x, axis=0, keepdims=True) #최솟값
x_scaled = (x - x_min)/ (x_max - x_min)
print(x_scaled)

[[0.  0. ]
 [0.5 0.5]
 [1.  1. ]]


* axis = 0 index방향 , axis = 1 column 방향 
* drop 의 axis는 레이블의 위치를 말하며, 사용하지않고 index, column으로 삭제하는게 용이.

In [166]:
df = pd.DataFrame(x, columns=['length', 'width'])
df

length  width
0       1      2
1       3      4
2       5      6

In [167]:
df.mean(axis=0)

length    3.0
width     4.0
dtype: float64

In [168]:
df.mean(axis=1)

0    1.5
1    3.5
2    5.5
dtype: float64

In [169]:
df.drop(labels=1, axis=0)  # axis: label이 있는 축.

length  width
0       1      2
2       5      6

In [170]:
df.drop(index=1)

length  width
0       1      2
2       5      6

In [171]:
df.drop(labels='length', axis=1)

width
0      2
1      4
2      6

In [172]:
df.drop(columns='length')

width
0      2
1      4
2      6

#Exercise

* seaborn 패키지의 iris 예제 데이터 셋을 로드
* iris 데이터프레임에서 species 변수를 제거
* iris 각 변수들을 표준화(standardization)
* iris 각 변수들을 정규화(normalization)

In [197]:
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [198]:
x = iris.drop(columns='species').values
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [202]:
x.index #row label

RangeIndex(start=0, stop=150, step=1)

In [203]:
x.columns #column label

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')

In [205]:
x= x.values #값들로만 이루어진 2차원 배열(2d ndarray)

In [206]:
x.shape

(150, 4)

In [192]:
# 표준화
mean = np.mean(x,axis=0,keepdims=True) #평균
std = np.std(x, axis=0, keepdims=True) #표준편차
print(mean)
print(std)

[[5.84333333 3.05733333 3.758      1.19933333]]
[[0.82530129 0.43441097 1.75940407 0.75969263]]


In [210]:
x_stand = (x-mean)/std # 각 변수들끼리 표준화
print(x_stand[:5, :])

[[-0.90068117  1.01900435 -1.34022653 -1.3154443 ]
 [-1.14301691 -0.13197948 -1.34022653 -1.3154443 ]
 [-1.38535265  0.32841405 -1.39706395 -1.3154443 ]
 [-1.50652052  0.09821729 -1.2833891  -1.3154443 ]
 [-1.02184904  1.24920112 -1.34022653 -1.3154443 ]]


In [212]:
np.mean(x_stand, axis=0)

array([-4.73695157e-16, -7.81597009e-16, -4.26325641e-16, -4.73695157e-16])

In [213]:
np.std(x_stand, axis=0)

array([1., 1., 1., 1.])

In [214]:
# 정규화
x_max = np.max(x, axis=0, keepdims=True) # 각 변수들에서 최댓값
#keepdims=True 차원을 유지하겠다.
x_min = np.min(x, axis=0, keepdims=True) # 각 변수들에서 최솟값
x_nor = (x-x_min)/ (x_max-x_min) # 정규화(min-max scaling)
x_nor[:5,:] #:5 행 , : 컬럼
# 최솟값 0 ~ 최댓값 1 사이에 균등하게 분포하는것이 정규화

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667]])

In [215]:
np.max(x_nor, axis=0)

array([1., 1., 1., 1.])

In [216]:
np.min(x_nor, axis=0)

array([0., 0., 0., 0.])

# 행렬 곱 (dot product)

## 1차원 배열에서의 행렬 곱

In [217]:
a = np.array([1,2,3])
b = np.array([2,2,2])

In [218]:
a @ b

12

In [219]:
np.dot(a,b) #함수

12

In [220]:
a.dot(b) #ndarray 메서드

12

## 2차원 배열에서의 행렬 곱

`(i,j) @ (j,k) = (i,k)`

In [222]:
a = np.arange(1,7).reshape((2,3))
print(a)

[[1 2 3]
 [4 5 6]]


In [224]:
b = np.ones(shape=(3,2))
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [225]:
a @ b # (2,3) @ (3,2) = (2,2)

array([[ 6.,  6.],
       [15., 15.]])

In [226]:
b @ a # (3,2) @ (2,3) = (3,3) # 행렬 곱이 되려면 2,2이 같아야하고 최종으로는 3,3이 나옴

array([[5., 7., 9.],
       [5., 7., 9.],
       [5., 7., 9.]])

## 2차원 배열과 1차원 배열의 행렬 곱

`(i,j) @ (j,)= (i,) # 2D @ 1D = 1D`

`(i,j) @ (j, 1) = (i,1) # 2D @ @2D = 2D`

In [228]:
a # (2,3) shape

array([[1, 2, 3],
       [4, 5, 6]])

In [230]:
b = np.array([1,2,1]) # (3, ) shape

In [237]:
b.shape

(3,)

In [231]:
a@b # (2,3) @ (3,) = (2,)

array([ 8, 20])

In [235]:
c = np.array([[1],
             [2],
             [1]]) # (3,1)

In [236]:
a @ c # (2,3) @ (3,1) = (2, 1)

array([[ 8],
       [20]])

In [238]:
a @ b [:, np.newaxis] #  == a @ c

array([[ 8],
       [20]])

# 행렬의 transpose

In [239]:
print(a)

[[1 2 3]
 [4 5 6]]


In [240]:
print(a.T) #transpose == T

[[1 4]
 [2 5]
 [3 6]]
